default_language_version:
    python: python3.12

# Define which files to include/exclude
default_stages: [pre-commit, pre-push]
default_install_hook_types: [pre-commit, pre-push]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://github.com/psf/black
      rev: 24.10.0
      hooks:
          - id: black
            files: ^backend/
            language_version: python3.12

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.8.0
      hooks:
          - id: ruff
            args: [--fix]
            files: ^backend/
            additional_dependencies: []

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.9.0
      hooks:
          - id: mypy
            files: ^backend/
            additional_dependencies:
                - types-sqlalchemy
                - types-requests
                - types-PyYAML
                - types-python-dateutil
                - types-psycopg2

    # Frontend hooks

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            files: ^frontend/
            additional_dependencies:
                - prettier@3.4.1
                - prettier-plugin-svelte@3.3.2
                - prettier-plugin-tailwindcss@0.6.9

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v9.15.0
      hooks:
          - id: eslint
            files: ^frontend/
            types: [file]
            types_or: [javascript, jsx, ts, tsx, svelte]
            additional_dependencies:
                - eslint@8.57.0
                - "@typescript-eslint/parser@7.1.0"
                - "@typescript-eslint/eslint-plugin@7.1.0"
                - "eslint-plugin-svelte@2.35.1"
                - "eslint-config-prettier@9.1.0"
