# Dockerfile.dev for frontend
FROM node:21-alpine

WORKDIR /app/frontend

RUN corepack enable && corepack prepare pnpm@latest --activate


# Install dependencies first (better layer caching)
COPY ./frontend/package.json ./frontend/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# The source code will be mounted in docker-compose
CMD ["pnpm", "run", "dev", "--", "--host", "0.0.0.0"]